In [4]:
A= [[] for i in range(1024)]
B=[[] for i in range(1024)]
C=[]
for i in range(1024):
    for j in range(1024):
        A[i].append(i)
        B[i].append(i+j)

In [5]:
import numpy as np

In [6]:
np.array(A) * np.array(B)

array([[      0,       0,       0, ...,       0,       0,       0],
       [      1,       2,       3, ...,    1022,    1023,    1024],
       [      4,       6,       8, ...,    2046,    2048,    2050],
       ...,
       [1042441, 1043462, 1044483, ..., 2084882, 2085903, 2086924],
       [1044484, 1045506, 1046528, ..., 2087946, 2088968, 2089990],
       [1046529, 1047552, 1048575, ..., 2091012, 2092035, 2093058]])

In [8]:
A = np.array(A)
B = np.array(B)

In [11]:
C = np.matmul(A, B)

In [13]:
C.shape

(1024, 1024)

In [14]:
C[100][100]

62617600

In [1]:
with open('output.raw', 'rb') as f:
    a = f.read()

In [2]:
b = []
for i in a:
    b.append(int(i))

In [3]:
import numpy as np
np.unique(np.array(b))

array([  3,  35,  75, 127, 186, 250])

In [6]:
import numpy as np
np.unique(np.array(b))

array([  3,  35,  75, 127, 186, 250])

In [9]:
a= np.array(a)

In [10]:
a.shape

()

In [8]:
import plotly.graph_objects as go

# Data
threads = [1, 4, 16, 64, 256]
execution_time_ns = [1383238290000, 433491396000, 347791980000, 200550032000, 193415494000]

# Convert nanoseconds to seconds for better readability
execution_time_sec = [time // 1_000_000_000 for time in execution_time_ns]

# Create the plot
fig = go.Figure()
fig.add_trace(go.Scatter(x=threads, y=execution_time_sec, mode='lines+markers'))

# Customize layout
fig.update_layout(
    title='Execution Time vs. Number of Threads',
    xaxis_title='Number of Threads',
    yaxis_title='Execution Time (seconds)',
    # xaxis=dict(tickmode='linear'),
    # yaxis=dict(dtick=1),
)

# Show the plot
fig.show()

In [4]:
execution_time_sec

[1383, 388, 340, 371, 366]